/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.halamanMasuk;

import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;

/**
 *
 * @author NANON
 */
public class signUpPage extends javax.swing.JPanel {

    /**
     * Creates new form signUpPage
     */
    public signUpPage() {
        initComponents();
    }
    
    public Object getBtnSignUp() {
        return btnSignUp;
    }
    
    public String getUsername() {
        return txUsername.getText();
    }
    
    public String getPassword() {
        return txPassword.getText();
    }
    
    public String getConfirmPassword() {
        return txCPassword.getText();
    }
    
    public String getName() {
        return txName.getText();
    }
    
    public String getNIP() {
        return txNIP.getText();
    }
    
    public int getDay() {
        return (Integer) spinDay.getValue();
    }
    
    public int getMonth() {
        return (Integer) spinMonth.getValue();
    }
    
    public int getYear() {
        return (Integer) spinYear.getValue();
    }
    
    public String getEmail() {
        return txEmail.getText();
    }
    
    public String getNumber() {
        return txNumber.getText();
    }
    
    public void reset() {
        cbType.setSelectedIndex(0);
        txUsername.setText("");
        txPassword.setText("");
        txCPassword.setText("");
        txNIP.setText("");
        txName.setText("");
        spinDay.setValue(1);
        spinMonth.setValue(1);
        spinYear.setValue(1970);
        txEmail.setText("");
        txNumber.setText("");
    }
    
    public void addAdapter(MouseAdapter e) {
        spinDay.addMouseListener(e);
        spinMonth.addMouseListener(e);
        spinYear.addMouseListener(e);
    }
    
    public void addListener(ActionListener e) {
        btnSignUp.addActionListener(e);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbType = new javax.swing.JComboBox<>();
        txUsername = new javax.swing.JTextField();
        txPassword = new javax.swing.JPasswordField();
        txCPassword = new javax.swing.JPasswordField();
        txNIP = new javax.swing.JTextField();
        txName = new javax.swing.JTextField();
        txEmail = new javax.swing.JTextField();
        spinDay = new javax.swing.JSpinner();
        txNumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        spinMonth = new javax.swing.JSpinner();
        spinYear = new javax.swing.JSpinner();
        btnSignUp = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));
        setPreferredSize(new java.awt.Dimension(400, 400));
        setLayout(null);

        cbType.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Silahkan pilih jenis...", "Manager Inventaris", "Koordinator Inventaris", "Pelapor" }));
        add(cbType);
        cbType.setBounds(117, 11, 264, 30);
        add(txUsername);
        txUsername.setBounds(117, 52, 264, 30);
        add(txPassword);
        txPassword.setBounds(117, 88, 264, 30);
        add(txCPassword);
        txCPassword.setBounds(117, 124, 264, 30);
        add(txNIP);
        txNIP.setBounds(117, 172, 264, 30);
        add(txName);
        txName.setBounds(117, 208, 264, 30);
        add(txEmail);
        txEmail.setBounds(117, 280, 264, 30);

        spinDay.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        add(spinDay);
        spinDay.setBounds(117, 244, 39, 30);
        add(txNumber);
        txNumber.setBounds(117, 316, 264, 30);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Daftar sebagai");
        add(jLabel1);
        jLabel1.setBounds(26, 18, 73, 16);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        add(jLabel2);
        jLabel2.setBounds(48, 60, 51, 16);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        add(jLabel3);
        jLabel3.setBounds(52, 96, 47, 16);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Confirm Password");
        add(jLabel4);
        jLabel4.setBounds(10, 132, 89, 16);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NIP");
        add(jLabel5);
        jLabel5.setBounds(82, 180, 17, 16);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nama");
        add(jLabel6);
        jLabel6.setBounds(69, 216, 30, 16);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tanggal Lahir");
        add(jLabel7);
        jLabel7.setBounds(33, 252, 66, 16);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Email");
        add(jLabel8);
        jLabel8.setBounds(71, 288, 28, 16);

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nomor Telp.");
        add(jLabel9);
        jLabel9.setBounds(38, 324, 61, 16);

        spinMonth.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        add(spinMonth);
        spinMonth.setBounds(171, 244, 39, 30);

        spinYear.setModel(new javax.swing.SpinnerNumberModel(1970, 1970, 2016, 1));
        add(spinYear);
        spinYear.setBounds(225, 244, 63, 30);

        btnSignUp.setBackground(new java.awt.Color(255, 255, 255));
        btnSignUp.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btnSignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new/Add User Male Filled-16 (2).png"))); // NOI18N
        btnSignUp.setText("DAFTAR");
        add(btnSignUp);
        btnSignUp.setBounds(10, 357, 371, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backregis.jpg"))); // NOI18N
        add(jLabel10);
        jLabel10.setBounds(0, 0, 400, 400);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignUp;
    private javax.swing.JComboBox<String> cbType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner spinDay;
    private javax.swing.JSpinner spinMonth;
    private javax.swing.JSpinner spinYear;
    private javax.swing.JPasswordField txCPassword;
    private javax.swing.JTextField txEmail;
    private javax.swing.JTextField txNIP;
    private javax.swing.JTextField txName;
    private javax.swing.JTextField txNumber;
    private javax.swing.JPasswordField txPassword;
    private javax.swing.JTextField txUsername;
    // End of variables declaration//GEN-END:variables
}
