/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.halamanMasuk;

import java.awt.event.ActionListener;

/**
 *
 * @author NANON
 */
public class signInPage extends javax.swing.JPanel {

    /**
     * Creates new form signInPage
     */
    public signInPage() {
        initComponents();
    }
    
    public Object getBtnSingIn() {
        return btnSignIn;
    }
    
    public String getUsername() {
        return txUsername.getText();
    }
    
    public String getPassword() {
        return txPassword.getText();
    }
    
    public void reset() {
        txUsername.setText("");
        txPassword.setText("");
    }
    
    public void addListener(ActionListener e) {
        btnSignIn.addActionListener(e);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txUsername = new javax.swing.JTextField();
        txPassword = new javax.swing.JPasswordField();
        btnSignIn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(9, 131, 109));
        setLayout(null);
        add(txUsername);
        txUsername.setBounds(90, 120, 280, 44);
        add(txPassword);
        txPassword.setBounds(90, 190, 280, 44);

        btnSignIn.setBackground(new java.awt.Color(255, 255, 255));
        btnSignIn.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btnSignIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new/Checked User Male Filled-16 (2).png"))); // NOI18N
        btnSignIn.setText("MASUK");
        add(btnSignIn);
        btnSignIn.setBounds(40, 270, 330, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/userimg.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(40, 120, 45, 45);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/passimg.jpg"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(40, 190, 45, 45);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backregis.jpg"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(0, 0, 400, 400);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txPassword;
    private javax.swing.JTextField txUsername;
    // End of variables declaration//GEN-END:variables
}
